"""Add manager_id to Team

Revision ID: 9133684eeda6
Revises: '003'
Create Date: 2026-09-17 16:32:21.958955

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9133684eeda6'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_teams_manager_id'), 'teams', ['manager_id'], unique=False)
    op.create_foreign_key(None, 'teams', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_teams_manager_id'), table_name='teams')
    op.drop_column('teams', 'manager_id')
    # ### end Alembic commands ###
